Dal
OpenGeekBrains/HR_in_pocket pull request #43
Opened 2020-11-10 22:10 UTC by MrAliev

Сущность "Задание"

2020-11-10 23:52 UTC, WolfManR commented
Заметил что в классе инициализации базы данных используется одинаковый шаблон действий для инициализации таблиц, это пока что игнорируется?

2020-11-11 15:30 UTC, Infarh requested changes

2020-11-11 15:30 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.DAL/Migrations/20201110220620_Add_TargetTask.cs
> +    }
Пустая миграция...

2020-11-11 15:30 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.DAL/Data/TestData.cs
> +                        Tarif = Tarifs[new Random().Next(0, Tarifs.Count-1)],
Создаём Random для каждой сущности заново?

2020-11-13 11:58 UTC, WolfManR commented on src/HRInPocket/Services/HRInPocket.DAL/Data/TestData.cs
> +                        Tarif = Tarifs[new Random().Next(0, Tarifs.Count-1)],
исправленно при слиянии с веткой Tarxos/DbInitializerOptimization

2020-11-13 12:20 UTC, WolfManR commented on src/HRInPocket/Services/HRInPocket.DAL/Migrations/20201110220620_Add_TargetTask.cs
> +    }
Исправленно при слиянии с веткой Tarxos/DALUpdateFix

2020-11-13 13:57 UTC, merged