dbinitializer optimization
OpenGeekBrains/HR_in_pocket pull request #45
Opened 2020-11-11 14:34 UTC by WolfManR

Оптимизация кода инициализатора базы данных

2020-11-11 15:26 UTC, Infarh requested changes

2020-11-11 15:26 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.DAL/Data/TestData.cs
> +                }));
```suggestion
           var rnd = new Random();
            __TargetTasks = Enumerable.Range(1, 50).Select(
                Source => new TargetTask
                {
                    Address = Addresses[rnd .Next(0, Addresses.Count)],
                    Speciality = Specialties[rnd .Next(0, Specialties.Count)],
                    CoverLetterLink = $"Ссылка на сопроводительное письмо {Source}",
                    ResumeLink = $"Ссылка на резюме {Source}",
                    Salary = rnd .Next(30, 301) * 1000,
                    CreateCoverLetter = true,
                    CreateResume = true,
                    Tags = string.Empty,
                    RemoteWork = rnd .Next(0, 100) % 2 == 0
                }).ToList();
```

2020-11-11 15:26 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.DAL/Data/TestData.cs
> +
```suggestion
var rnd = new Random();
```

2020-11-11 15:26 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.DAL/Data/TestData.cs
> +                        TargetTask = (Source % 3 == 0) ? TargetTasks[Source / 3] : null
```suggestion
                        Speciality = Specialties.GetRange(Source % (Specialties.Count - 5), Source % 4).ToList(),
                        Tarif = Tarifs[rnd.Next(0, Tarifs.Count)],
                        TargetTask = (Source % 3 == 0) ? TargetTasks[Source / 3] : null  
```

2020-11-11 15:26 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.DAL/Migrations/20201110220620_Add_TargetTask.cs
> +    }
Пустая миграция нам зачем?

2020-11-11 15:28 UTC, Infarh commented
Очень расточительно создавать каждый раз Random для одного обращения к нему. Зачем?

2020-11-11 18:51 UTC, WolfManR commented
оу, тестовые данные тоже поправить надо?

2020-11-12 08:09 UTC, WolfManR commented
а я понял не туда реквест ложу

2020-11-12 08:09 UTC, closed without merging