Подключение десктопного приложения к парсеру.
OpenGeekBrains/HR_in_pocket pull request #62
Opened 2020-11-16 05:33 UTC by mnocard

2020-11-16 12:16 UTC, Infarh requested changes

2020-11-16 12:16 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Interfaces/IParsehh.cs
> +        event Action<Vacancy> Result;
События лучше делать с использованием делегата EventHandler<T>, где T - класс-наследник EventArgs. В этом случае такие события будут легко интегрироваться со стандартными обработчиками платформы. Да и другим будет воспринимать их легче.

2020-11-16 12:16 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/ParsehhService.cs
> +        readonly string HHUrl = "https://hh.ru/search/vacancy";
```suggestion
        private const string HHUrl = "https://hh.ru/search/vacancy";
```

2020-11-16 12:16 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/ParsehhService.cs
> +        public async void Parse(string GetParameters=null)
Нужно переделать метод так, чтобы он возвращал задачу
```suggestion
        public async Task Parse(string GetParameters=null)
```

2020-11-16 12:16 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/ParsehhService.cs
> +                var items = document.QuerySelectorAll("div")
```C#
document.QuerySelectorAll("div.vacancy-serp-item")
```
Или так
```C#
document.QuerySelectorAll("div[class=vacancy-serp-item]")
```
?

2020-11-16 12:16 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/ParsehhService.cs
> +                        var _vacancyname = VacancyNameParse.TextContent;
Локальные переменные - зачем имена с подчёркивания начинать? С подчёркивания начинаются имена полей классов приватные. Локальные переменные в нижнем регистре, слова разделяются подчёркиванием.

2020-11-16 12:16 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/ParsehhService.cs
> +                                    ulong.TryParse(CompensationString,out CompensationUp);
А если не получится преобразовать, то что делать? Исключение FormatException надо... И обработку его выше по стеку вызова.

2020-11-16 12:16 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/ParsehhService.cs
> +                                if (CompensationStringSplit.GetLength(0)>1)
```suggestion
                                if (CompensationStringSplit.Length > 1)
```

2020-11-16 12:16 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/ParsehhService.cs
> +                        Result?.Invoke(vacancy);
Для генерации события надо написать отдельный метод virtual void InvokeResult принимающий объект-наследник класса EventArgs. И генерировать событие исключительно в нём.

2020-11-16 12:16 UTC, Infarh commented on src/HRInPocket/Test/AngleSharp-Console-Test/AngleSharp-Console-Test/Program.cs
> +        private static void getResult(Vacancy obj)
Имена методов с большой буквы должны быть.

2020-11-16 12:16 UTC, Infarh commented on src/HRInPocket/UI/WPF/HRInPocket.WPF/Services/SaveDataToJSON.cs
> +        public bool SaveDataToFile<T>(IEnumerable<T> data, string fileName)
Имена входных переменных в методе - либо все малые буквы, либо PascalCase

2020-11-16 12:16 UTC, Infarh commented on src/HRInPocket/UI/WPF/HRInPocket.WPF/Services/SaveDataToJSON.cs
> +            using (StreamWriter file = File.CreateText(fileName + "--" + DateTime.Now.ToString("yyyy-MM-dd--HH-mm") + ".json"))
```suggestion
            using (StreamWriter file = File.CreateText($"{filename}--{DateTime.Now:yyyy-MM-dd--HH-mm}.json")
```

2020-11-16 12:16 UTC, Infarh commented on src/HRInPocket/UI/WPF/HRInPocket.WPF/ViewModels/MainWindowViewModel.cs
> +        #region Сервис сохранения данных
Регионы лучше заменить на комментарии в виде
```C#
/// <summary>Комментарий</summary>
```

2020-11-16 12:26 UTC, Dmitry-Ischenko commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/ParsehhService.cs
> +                var items = document.QuerySelectorAll("div")
`var items = document.QuerySelectorAll("div")
                    .Where(item => item.ClassName != null && (item.ClassName
                        .Equals("vacancy-serp-item") || item.ClassName.Contains("vacancy-serp-item ")));`
Там более сложное условие, если написать просто document.QuerySelectorAll("div[class=vacancy-serp-item]"), то придется все остальное переписывать, и добавлять дополнительные проверки. В таком виде он гарантированно разбирает на отдельные элементы, а в случае, если что-то пойдет не так, и не найдет не одного элемента, то foreach  не сработает.

2020-11-16 12:28 UTC, Dmitry-Ischenko commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/ParsehhService.cs
> +                        var _vacancyname = VacancyNameParse.TextContent;
Я решил, что мне так будет удобней выбрать переменные, значение которых нужно будет вернуть, и не запутаться. Переименовать?

2020-11-16 12:28 UTC, Dmitry-Ischenko commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/ParsehhService.cs
> +                        Result?.Invoke(vacancy);
принято

2020-11-16 12:29 UTC, Dmitry-Ischenko commented on src/HRInPocket/Test/AngleSharp-Console-Test/AngleSharp-Console-Test/Program.cs
> +        private static void getResult(Vacancy obj)
Принято

2020-11-16 12:30 UTC, Dmitry-Ischenko commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/ParsehhService.cs
> +        public async void Parse(string GetParameters=null)
Принято

2020-11-16 12:30 UTC, Dmitry-Ischenko commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/ParsehhService.cs
> +        readonly string HHUrl = "https://hh.ru/search/vacancy";
Принято

2020-11-16 12:30 UTC, Dmitry-Ischenko commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Interfaces/IParsehh.cs
> +        event Action<Vacancy> Result;
Принято

2020-11-17 15:30 UTC, Dmitry-Ischenko commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/ParsehhService.cs
> +                                    ulong.TryParse(CompensationString,out CompensationUp);
0 будет

2020-11-17 16:11 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/ParsehhService.cs
> +                                    ulong.TryParse(CompensationString,out CompensationUp);
А это корректно - в случае ошибки формата строки принимать за результат "0"?

2020-11-17 16:13 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/ParsehhService.cs
> +                                    ulong.TryParse(CompensationString,out CompensationUp);
Просто обычно данный метод используется в следующем сценарии:
```C#
if(!ulong.TryParse(str_value, out var value))
    throw new FormatException("Ошибка формата строки значения такого-то");
```
И в случае проблем сразу будет понятно, что данные были некорректные и и какие именно данные.

2020-11-17 16:41 UTC, Dmitry-Ischenko commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/ParsehhService.cs
> +                                    ulong.TryParse(CompensationString,out CompensationUp);
Добавил обработку исключений, и сообщение об исключение, в случае получение неожиданных данных

2020-11-18 15:54 UTC, Infarh approved these changes

2020-11-18 16:05 UTC, merged