Parser refactoring
OpenGeekBrains/HR_in_pocket pull request #69
Opened 2020-11-24 08:57 UTC by mnocard

Переработка парсера и WPF приложения в соответствии с требованиями #50

2020-11-25 08:54 UTC, MrAliev requested changes
1. Необходимо вынести код вывода вакансии на консоль в отдельный метод.
2. Для остановки парсера  хорошо бы вызвать s_cts.Cansel();
3. Жестко заданные константы рандомайзера в парсере - хорошо бы вынести в параметры со значениями по-умолчанию, для возможности изменения таковых из вызывающего кода

2020-11-25 10:10 UTC, mnocard commented
Добавлены методы возвращающие IAsyncEnumerable<Vacancy> и Task<(Vacancy[], string)>

2020-11-25 10:11 UTC, WolfManR commented
- уберите привязку у интерфейсов к hh.ru
- поправьте namespace у моделей

2020-11-25 10:19 UTC, mnocard commented
> * уберите привязку у интерфейсов к hh.ru
Вы имеете в виду комментарии? Парсер работает только с hh.ru, на других сайтах он работать должным образом не будет...

2020-11-25 10:22 UTC, WolfManR commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Models/Company.cs
> +namespace HRInPocket.Parsing.hh.ru.Models.Entites
здесь

2020-11-25 10:22 UTC, WolfManR commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Models/Vacancy.cs
> +namespace HRInPocket.Parsing.hh.ru.Models.Entites
здесь

2020-11-25 10:22 UTC, WolfManR commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Models/Metadata.cs
> +namespace HRInPocket.Parsing.hh.ru.Models.Entites
здесь

2020-11-25 10:22 UTC, WolfManR commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/Parsehh.cs
> +        protected virtual void OnVacancyEventArgs(Vacancy vacancy)
замените имя методу на более ясное

2020-11-25 10:22 UTC, WolfManR commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/Parsehh.cs
> +                Trace.TraceError(e.ToString());
возможно обработку Exception лучше доверить коду выше по уровню

2020-11-25 10:22 UTC, WolfManR commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/Parsehh.cs
> +                throw e;
перебрасывать Exception лучше не указывая явно throw **e**, а просто указав throw, тогда не будет потерян StackTrace, а ещё лучше вложить полученный Exception в созданный Exception типа ParseHHVacancyException в InnerException

2020-11-25 10:22 UTC, WolfManR commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/Parsehh.cs
> +        }
эти методы имеют одинаковую функциональность

2020-11-25 10:24 UTC, WolfManR commented
сам парсер может и не будет работать с другими сайтами, но интерфейс не обязан быть привязан к одному сайту

2020-11-25 15:58 UTC, Infarh approved these changes

2020-11-25 15:58 UTC, Infarh commented on src/HRInPocket/Test/AngleSharp-Console-Test/AngleSharp-Console-Test/Program.cs
>          static void Main()
```suggestion
        static async Task Main()
```

2020-11-25 15:58 UTC, Infarh commented on src/HRInPocket/Test/AngleSharp-Console-Test/AngleSharp-Console-Test/Program.cs
> +            _ = parse.ParseAsync(s_cts.Token, "https://hh.ru/search/vacancy");
```suggestion
            await parse.ParseAsync(s_cts.Token, "https://hh.ru/search/vacancy");
```

2020-11-25 16:01 UTC, WolfManR commented on src/HRInPocket/Test/AngleSharp-Console-Test/AngleSharp-Console-Test/Program.cs
>          static void Main()
можно и в топ - лвл изменить

2020-11-26 18:51 UTC, mnocard commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/Parsehh.cs
> +        }
``C#
Task ParseAsync(CancellationToken token, string page, string GetParameters) ``
Устарел и использоваться скорее всего не будет.
``C#
Task<(Vacancy[], string)> ParseAsync(CancellationToken token, string page)``
Перебирает только одну страницу и не перепрыгивает автоматом на следующую. 
``C#
IAsyncEnumerable<Vacancy> ParseEnumerableAsync([EnumeratorCancellation] CancellationToken token, string page, string GetParameters)``
Возвращает данные через IAsyncEnumerable и автоматически парсит страницы с автоматическим переходом на следующую.

Методы очень похожи, но назначение разное. Не знаю, как еще сильней упростить повторяющийся код.

2020-11-26 18:52 UTC, mnocard commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/Parsehh.cs
> +        }
`Task ParseAsync(CancellationToken token, string page, string GetParameters)`
Этот метод вообще, думаю, можно удалить...

2020-11-26 20:47 UTC, WolfManR commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/Parsehh.cs
> +        }
раз не используется можно и удалить, либо пометить атрибутом obsolette,
а на счёт идеи как вытащить больше повторяющегося кода:

- привести к почти абсолютно идентичному виду
- вытащить рандом в поле
- разобрать логически повторяющееся по локальным функциям
- перебрать итог и вытащить идентичные функции за предел методов
- понять что именно и где должно отлавливатся и должно ли отлавливаться

2020-11-27 05:28 UTC, mnocard commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/Parsehh.cs
> +        }
Я сократил код еще, но пришлось довольно много полей сделать статическими. Не знаю, является ли это лучшим решением, но другого я не нашел.
Взгляните на этот коммит https://github.com/OpenGeekBrains/HR_in_pocket/pull/69/commits/fe75f6008c9e1817a22ff91377868e8066ed7256

2020-11-27 09:23 UTC, mnocard commented on src/HRInPocket/Services/HRInPocket.Parsing.hh.ru/HRInPocket.Parsing.hh.ru/Service/Parsehh.cs
> +        public async Task<(Vacancy[], string)> ParseAsync(CancellationToken token, string page, int MinWaitTime = 300, int MaxWaitTime = 2000)
Время задержки выведено в параметры со значением по умолчанию

2020-11-27 09:23 UTC, mnocard commented on src/HRInPocket/Test/AngleSharp-Console-Test/AngleSharp-Console-Test/Program.cs
> +            s_cts.Dispose();
Добавлен токен отмены и реализовано его использование

2020-11-27 17:56 UTC, MrAliev approved these changes

2020-11-27 17:58 UTC, merged