Чистка кода
OpenGeekBrains/HR_in_pocket pull request #76
Opened 2020-11-28 17:30 UTC by WolfManR

2020-11-30 10:35 UTC, Infarh requested changes

2020-11-30 10:35 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Interfaces/Services/Repository/IRepository.cs
> +    public interface IRepository<TDto> where TDto: BaseDTO
Если в параметре типа используется ограничение на то, что TDto должно быть BaseDTO, то интерфейс следует обозвать IDtoRepository

2020-11-30 10:35 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Interfaces/Services/Repository/IResumeService.cs
> +        Task SearchResumesAsync();
Фильтр в метод надо добавить...

2020-11-30 10:35 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Interfaces/Services/Repository/ITargetTaskService.cs
> +    public interface ITargetTaskService : IRepository<TargetTaskDTO>
Нужны ещё методы запуска и остановки сервиса, а также свойство, характеризующее его текущее состояние. Либо, быть может, имеет смысл разделить на сервис, который чисто манипулирует сущностями Заданий (даёт посмотреть, добавить, удалить, найти по заданному критерию - по сути, репозиторий) и сервис, который выполняет эти задания (TaskRunner).

2020-11-30 10:35 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Services/Repositories/CompanyService.cs
> +                /*Логика фильтрации после понимания структуры фильтров*/
А не стоит ли эту логику прямо в этот класс фильтра и засунуть? Пусть фильтр занимается тем, что фильтрует переданный ему запрос и возвращает уже преобразованный - с наложенными на него фильтрами.

2020-11-30 10:35 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Services/Repositories/CompanyService.cs
> +                Entities = query.Select(q => _Mapper.Map<CompanyDTO>(q)),
```suggestion
                Entities = query.Select(_Mapper.Map<CompanyDTO>),
```

2020-11-30 10:35 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Services/Repositories/DataRepository.cs
>              table.Remove(item);
Можно удалить сущность не загружая её из БД в контекст примерно следующим образом
```C#
_DbContext.Entity(new TEntity { Id = id }).State = EntityState.Deleted;
_DbContext.SaveChanges();
```

2020-11-30 10:35 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Services/Repositories/DataRepository.cs
> +        public void CreateRange(ICollection<TEntity> items)
```suggestion
        public void CreateRange(IEnumerable<TEntity> items)
```

2020-11-30 10:35 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Services/Repositories/DataRepository.cs
> +        public async Task CreateRangeAsync(ICollection<TEntity> items)
```suggestion
        public async Task CreateRangeAsync(IEnumerable<TEntity> items)
```

2020-11-30 10:35 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Services/Repositories/ResumeService.cs
> +                Entities = query.Select(q => _Mapper.Map<ResumeDTO>(q)),
```suggestion
                Entities = query.Select(_Mapper.Map<ResumeDTO>),
```

2020-11-30 10:35 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Services/Repositories/ResumeService.cs
>              var query = _DataProvider.GetQueryable();
Быть может это тоже стоит убрать в фильтр? Сделать универсальный базовый класс фильтра, способный накладывать постраничное разбиение на запрос.
Что-нибудь типа 
```C#
public async Task<(IQueryable<T> Query, int TotalCount)> Paging(IQueryable<T> query, int Page, int PageSize)
{
    var total_count = await query.CountAsync();
    var result = query.Skip(Page * PageSize).Take(PageSize);
    return (result, total_count);
}
```

2020-11-30 10:35 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Services/Repositories/ResumeService.cs
> +            .Select(r => _Mapper.Map<ResumeDTO>(r));
```suggestion
            .Select(_Mapper.Map<ResumeDTO>);
```

2020-12-02 16:02 UTC, Infarh approved these changes

2020-12-06 21:53 UTC, WolfManR commented on src/HRInPocket/Services/HRInPocket.Interfaces/Services/Repository/ITargetTaskService.cs
> +    public interface ITargetTaskService : IRepository<TargetTaskDTO>
исправляется в пулле #81

2020-12-06 21:53 UTC, WolfManR commented on src/HRInPocket/Services/HRInPocket.Interfaces/Services/Repository/IResumeService.cs
> +        Task SearchResumesAsync();
исправляется в пулле #81

2020-12-06 22:19 UTC, Infarh approved these changes

2020-12-06 22:19 UTC, Infarh commented on src/HRInPocket/Common/HRInPocket.Domain/Filters/Filter.cs
> +            var (page, pageSize) = (Pages.PageNumber, Pages.PageSize);
Вот это вообще непонятно зачем. Зачем вводить локальные переменные?

2020-12-06 22:19 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.DAL/Data/TestDbInitializer.cs
> +                .InitTable(TestData.Price)
Мне не нравится что внутри этих методов нельзя пользоваться логгером. Этот метод более нигде не применим. Может быть его реализовать просто как метод класса инициализатора и там будет тогда возможность добавить логирование?

2020-12-06 22:19 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Services/Repositories/Base/DataRepository.cs
> +            return true;
А этот метод вообще может вернуть false?

2020-12-06 22:19 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Services/Repositories/Base/DataRepository.cs
> +                throw new ArgumentNullException(nameof(item));
А Вот тут стоило бы вернуть false

2020-12-06 22:19 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Services/Repositories/Base/DataRepository.cs
> +            return true;
Тут тоже bool-результат бессмысленен.

2020-12-06 22:19 UTC, Infarh commented on src/HRInPocket/Services/HRInPocket.Services/Repositories/ResumeService.cs
> +            .Select(_Mapper.Map<ResumeDTO>);
У AutoMapper'а есть пакет, позволяющий выполнять те же самые действия, но внутри запроса EF.
То ли AutoMapper.Extensions.ExpressionMapping, то ли AutoMapper.Data, то ли AutoMapper.Collection.EntityFrameworkCore
AutoMapper.AspNetCore.OData.EFCore

2020-12-06 22:19 UTC, Infarh commented on src/HRInPocket/UI/WEB/HRInPocket/Controllers/API/AccountApiController.cs
> +    public class LoginException : AuthorizationException
👍

2020-12-06 22:19 UTC, Infarh commented on src/HRInPocket/UI/WEB/HRInPocket/Controllers/API/AssignmentsApiControllers.cs
> +    [ModelBinder(typeof(AssignmentTypeModelBinder))]
👍

2020-12-06 22:25 UTC, WolfManR commented on src/HRInPocket/Common/HRInPocket.Domain/Filters/Filter.cs
> +            var (page, pageSize) = (Pages.PageNumber, Pages.PageSize);
предложение решарпера, всегда просит разобрать модель на запчасти

2020-12-06 22:27 UTC, WolfManR commented on src/HRInPocket/Services/HRInPocket.Services/Repositories/Base/DataRepository.cs
> +            return true;
исправляется в пулле #81

2020-12-06 22:28 UTC, WolfManR commented on src/HRInPocket/Services/HRInPocket.Services/Repositories/Base/DataRepository.cs
> +            return true;
перенаправить в #81

2020-12-06 22:28 UTC, WolfManR commented on src/HRInPocket/Services/HRInPocket.Services/Repositories/Base/DataRepository.cs
> +                throw new ArgumentNullException(nameof(item));
перенаправить в #81

2020-12-06 22:29 UTC, WolfManR commented on src/HRInPocket/UI/WEB/HRInPocket/Controllers/API/AccountApiController.cs
> +    public class LoginException : AuthorizationException
предложите чем-то уже сейчас дополнить?

2020-12-06 22:30 UTC, WolfManR commented on src/HRInPocket/Common/HRInPocket.Domain/Filters/Filter.cs
> +            var (page, pageSize) = (Pages.PageNumber, Pages.PageSize);
убрать? а как в решарпере убрать эту предложение?

2020-12-06 22:58 UTC, WolfManR commented
планы:
 - добавить логирование
 - вытащить модели и сервисы
 - скорректировать работу написанных сервисов
 - добавить логической функциональности сервисам и моделям

2020-12-07 18:54 UTC, WolfManR commented on src/HRInPocket/Services/HRInPocket.DAL/Data/TestDbInitializer.cs
> +                .InitTable(TestData.Price)
исправлено в коммитах f06ffff & 38ffda3

2020-12-09 16:03 UTC, Infarh requested changes

2020-12-09 16:03 UTC, Infarh commented on src/HRInPocket/UI/WEB/HRInPocket/Infrastructure/Models/LogEvents.cs
> +    }
Может быть стоит переделать этот класс в enum?

2020-12-09 16:03 UTC, Infarh commented on src/HRInPocket/UI/WEB/HRInPocket/Infrastructure/Models/Records/Assignments/Assignment.cs
> +        public int number_of_invitations { get; set; }
Record со свойствами с возможностью записи?

2020-12-09 16:03 UTC, Infarh commented on src/HRInPocket/UI/WEB/HRInPocket/Infrastructure/Models/Records/FeedbackRequest.cs
> +        public DateTime ApplicantAssignedDate { get; set; }
Аналогично...

2020-12-09 16:03 UTC, Infarh commented on src/HRInPocket/UI/WEB/HRInPocket/Infrastructure/Models/Records/NotifyUser.cs
> +        public bool PushNotify { get; set; }
```suggestion
        public bool EmailNotify { get; init; }
        public bool SmsNotify { get; init; }
        public bool PushNotify { get; init; }
```

2020-12-09 19:16 UTC, WolfManR commented on src/HRInPocket/UI/WEB/HRInPocket/Infrastructure/Models/LogEvents.cs
> +    }
оказалось нельзя

2020-12-09 19:17 UTC, WolfManR commented on src/HRInPocket/UI/WEB/HRInPocket/Infrastructure/Models/Records/Assignments/Assignment.cs
> +        public int number_of_invitations { get; set; }
временные модели, по причине характера использования изменить нельзя

2020-12-09 19:17 UTC, WolfManR commented on src/HRInPocket/UI/WEB/HRInPocket/Infrastructure/Models/Records/FeedbackRequest.cs
> +        public DateTime ApplicantAssignedDate { get; set; }
временные модели, по причине характера использования изменить нельзя

2020-12-09 20:27 UTC, Infarh approved these changes

2020-12-09 20:27 UTC, Infarh commented on src/HRInPocket/UI/WEB/HRInPocket/Controllers/API/AssignmentsApiControllers.cs
> +            _assignmentsManager = new AssignmentsManagerService(_applicantsManager);
Стоит разместить в контейнере Ioc

2020-12-09 20:37 UTC, WolfManR commented on src/HRInPocket/UI/WEB/HRInPocket/Controllers/API/AssignmentsApiControllers.cs
> +            _assignmentsManager = new AssignmentsManagerService(_applicantsManager);
я помню

2020-12-10 18:30 UTC, merged